# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ggregator.proto\x12\x02\x61i\"<\n\nFaceResult\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12\x11\n\tredis_key\x18\x03 \x01(\t\"&\n\x12\x46\x61\x63\x65ResultResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32L\n\nAggregator\x12>\n\x12SaveFaceAttributes\x12\x0e.ai.FaceResult\x1a\x16.ai.FaceResultResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FACERESULT']._serialized_start=24
  _globals['_FACERESULT']._serialized_end=84
  _globals['_FACERESULTRESPONSE']._serialized_start=86
  _globals['_FACERESULTRESPONSE']._serialized_end=124
  _globals['_AGGREGATOR']._serialized_start=126
  _globals['_AGGREGATOR']._serialized_end=202
# @@protoc_insertion_point(module_scope)
